CREATE DATABASE db_mii2an;

USE db_mii2an;

CREATE TABLE CLIENTES (
ID_CLIENTE INT UNSIGNED PRIMARY KEY auto_increment,
NOME VARCHAR(70) NOT NULL,
CPF CHAR(11) UNIQUE NOT NULL,
SENHA CHAR(8) NOT NULL,
CONFIRMA_SENHA CHAR(8) NOT NULL
);

SHOW TABLES;

SELECT * FROM clientes;